language: generic
sudo: false
git:
  depth: 10

os:
  - linux
  - osx

before_script:
  - git clone --depth=1 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis
  - (if ! test -d $HOME/vim-$VIM_VERSION/bin; then
      git clone https://github.com/vim/vim $HOME/vim &&
      cd $HOME/vim &&
      git checkout v$VIM_VERSION &&
      ./configure --prefix=$HOME/vim-$VIM_VERSION &&
      make &&
      make install;
    fi)

cache:
  directories:
    - $HOME/vim-$VIM_VERSION

env:
  - VIM_VERSION=8.1.1539

script:
  - export PATH=$HOME/vim-$VIM_VERSION/bin:$PATH
  - vim --version
  - /tmp/vim-themis/bin/themis
